import dotenv from 'dotenv'
import { readFileSync } from 'fs'
import { fileURLToPath } from 'url'
import { dirname, resolve } from 'path'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)

// 1. Try the local .env file (development)
try { dotenv.config({ path: resolve(__dirname, '../../.env') }) } catch {}

// 2. Try the build-injected snapshot (generated by scripts/generate-env.js on Vercel).
//    Vercel bundles the full server/ directory, so readFileSync works at runtime.
let buildSnapshot = {}
try {
  buildSnapshot = JSON.parse(readFileSync(resolve(__dirname, '../build-vars.json'), 'utf-8'))
} catch {}

// 3. Check for config keys in order of precedence:
//    - real process.env (Vercel dashboard or host OS)
//    - VITE_ prefixed (from the build snapshot or local .env)
//    - empty fallback
const env = (key) => {
  // Real process.env (set on Vercel dashboard or locally)
  if (process.env[key]) return process.env[key]
  // VITE_ prefixed (from build snapshot or local .env)
  const prefixed = `VITE_${key}`
  if (process.env[prefixed]) return process.env[prefixed]
  // Build snapshot - check both VITE_ and non-prefixed
  if (buildSnapshot[key]) return buildSnapshot[key]
  if (buildSnapshot[prefixed]) return buildSnapshot[prefixed]
  return ''
}

export const config = {
  port: process.env.PORT || 3000,
  supabaseUrl: env('SUPABASE_URL'),
  supabaseAnonKey: env('SUPABASE_ANON_KEY'),
  supabaseServiceRole: env('SUPABASE_SERVICE_ROLE'),
  jwtSecret: process.env.JWT_SECRET,
  corsOrigins: process.env.CORS_ORIGINS?.split(',') || ['*'],
  smtpHost: process.env.SMTP_HOST,
  smtpPort: process.env.SMTP_PORT,
  smtpUser: process.env.SMTP_USER,
  smtpPass: process.env.SMTP_PASS,
  adminEmail: process.env.ADMIN_EMAIL || 'admin@alihassan.dev',
}
