// Generates api/env.js — sets process.env vars at import time.
// Statically imported from api/index.js, so Vercel's tracer bundles it.
import { writeFileSync } from 'fs'
import { resolve, dirname } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const root = resolve(__dirname, '..')

const pairs = [
  ['VITE_SUPABASE_URL', 'SUPABASE_URL'],
  ['VITE_SUPABASE_ANON_KEY', 'SUPABASE_ANON_KEY'],
  ['VITE_SUPABASE_SERVICE_ROLE', 'SUPABASE_SERVICE_ROLE'],
  ['JWT_SECRET', 'JWT_SECRET'],
]

const lines = []
for (const [buildKey, runtimeKey] of pairs) {
  const val = process.env[buildKey]
  if (val) {
    lines.push(`process.env['${buildKey}'] = ${JSON.stringify(val)};`)
    lines.push(`process.env['${runtimeKey}'] = ${JSON.stringify(val)};`)
  }
}

if (lines.length) {
  const code = `// Auto-generated by scripts/generate-env.js\n${lines.join('\n')}\n`
  writeFileSync(resolve(root, 'api/env.js'), code)
  console.log('[generate-env] Wrote api/env.js')
}
